### PR TITLE
forward missing methods to the root element

### PR DESCRIPTION
**Pull request by Cohen-Carlisle**
this allows syntax such as:
@current_page.page_section.visible?
@current_page.page_section.click

### CODE REVIEW

**Comment by tk8817** [comment]
My team was just about to submit this same PR, awesome stuff.

**Comment by Cohen-Carlisle** [comment]
I was looking for a different way to do this. However, `Element` methods are split into 3 classes presently (`PageObject::Elements::Element`, `PageObject::Platforms::WatirWebDriver::Element`, and `PageObject::Platforms::SeleniumWebDriver::Element`). I could union the `instance_methods` of all 3 classes... then define only those are not yet defined when `page-object.rb` is read...

Any opinions?

**Comment by daneandersen** [comment]
I'm inclined to think the method_missing approach is the most flexible and resilient to change, but my understanding is it's slower than direct delegation. Is that your goal in finding a different approach? Or is there something else you hope to gain?

**Comment by daneandersen** [comment]
I just fixed the issue with the listen gem that was causing tests to fail. it was trying to use a version that didn't work in the versions of ruby we're testing in. If you pull the code in master, it should help.

**Comment by Cohen-Carlisle** [comment]
I've always considered `method_missing` a bit scary, especially since it occurs dynamically at messaging-time (I think I just made that up) instead of statically when the class is defined. But if agrees its a suitable approach then :+1:

**Comment by Cohen-Carlisle** [comment]
Merged master, fixed coverage by adding tests, fixed a bug, added more tests for the fixed bug.

**Comment by cheezy** [comment]
Merged.  Hoping to get the release out today or tomorrow.

**Comment by Cohen-Carlisle** [comment]
@cheezy any update on this release? I would love to delete my `page-object` monkey patches and use `1.1.2`.

**Comment by tk8817** [comment]
@Cohen-Carlisle just call master in your gemfile

```gem 'page-object',     github: 'cheezy/page-object' ```

**Pull request merged**
