### PR TITLE
Change select_list 'select' to support 'value' along with 'text'

### PR DESCRIPTION
**Pull request by vveliev**
I have run into the  problem when select list 'text' is rendered differently in different browsers.
#350

### CODE REVIEW

**Comment by vveliev** [comment]
@titusfortner Hey do you mind to have a glance  why watir test is failing ?!

**Comment by titusfortner** [comment]
It looks like this PR is for Selenium code, not Watir? Let's continue this investigation on #350

**Comment by cheezy** [comment]
I'd be happy to include this if you also add support for watir-webdriver.

**Comment by vveliev** [comment]
@titusfortner updates on watir side?

**Comment by cheezy** [comment]
Is this in good shape?  Working with both Selenium and Watir?

**Comment by vveliev** [comment]
selenium working , never looked in to watir side

**Comment by vveliev** [comment]
looks like this no longer needed ....

**Pull request closed without merging**
