### PR TITLE
adds array methods to section collections

### PR DESCRIPTION
**Pull request by Cohen-Carlisle**
also fixes section collection filename to follow convention
and misc whitespace fixes in files modified for these changes

### CODE REVIEW

**Comment by Cohen-Carlisle** [comment]
I'm not sure if @coveralls is drunk or I'm too stupid to understand its infinite wisdom. The reported coverage decrease appears to be due to the change in the way SectionCollections are instantiated for selenium [here](https://github.com/cheezy/page-object/pull/361/files#diff-683a96b31d6fef173af0eca3d3591082L1029), but no such decrease was reported for the analogous change in for watir. ¯\\\_(ツ)_/¯

I'm also fairly confident I didn't break `wait_for_ajax` for jruby, which is the only error failing the Travis CI build. ¯\\\_(ツ)_/¯

**Comment by Cohen-Carlisle** [comment]
Is anyone there?

**Comment by Cohen-Carlisle** [comment]
:skull:

**Comment by cheezy** [comment]
Thanks for this.  I've merged it.  I hope to make a release this week.

**Comment by cheezy** [comment]
Would you mind putting on the wiki about this?

**Comment by Cohen-Carlisle** [comment]
Made a very small change [here](https://github.com/cheezy/page-object/wiki/Page-Sections/_compare/7fad5145ddf2e78b0d6b78783d76cee134148637...d1fbf012e295f2c046af7c33fb42feaaa2aba505), which seemed to be the only place section collections were specifically mentioned.

**Pull request merged**
