### PR TITLE
Test Auto build on patched Ruby version

### PR DESCRIPTION
**Pull request by nicolasleger**

### CODE REVIEW

**Comment by bootstraponline** [comment]
Why are you downgrading the ruby versions?

**Comment by nicolasleger** [comment]
No, it doesn't downgrade, specifying so Travis will auto select the latest patch for those Ruby versions.
So we will not have to change it later for each minor patched rolled out.

**Comment by bootstraponline** [comment]
2.2.0 instead of 2.2.3 looks like a downgrade to me.

```
$ ruby --version
ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-linux]
```

https://travis-ci.org/cheezy/page-object/jobs/86102083

**Comment by titusfortner** [comment]
Expected behavior is here: https://rvm.io/rvm/basics
"If you use just the Major.Minor version numbers, RVM checks for, and uses, what is the most current patchlevel in its $rvm_path/config/db for that Major.Minor version."

But Travis uses --fuzzy which according to: https://github.com/rvm/rvm/issues/2746
"the --fuzzy flag is there to relax the checking, by default rvm forces latest version / patchlevel, with fuzzy it is relaxed and any "similar" version is selected."

Which means it is using what it finds instead of actually the latest.

**Pull request merged**
