### PR TITLE
Attempt at watir 6.0.0 resolving watir-webdriver depreciation

### PR DESCRIPTION
**Pull request by MacCracken**
Watir 6.0.0
Selenium-Webdriver 3.0.0
gemspec cleanup
renamed *watir_webdriver to watir
version up to 2.0.0 to keep space for previous webdrivers version bumping.

### CODE REVIEW

**Comment by MacCracken** [comment]
Attempts at bringing page-object the latest and greatest webdrivers

**Comment by tk8817** [comment]
@MacCracken - we made almost the exact same changes you guys did back in September (https://github.com/automation-wizards/page-object/commits/update_to_watir). I would be interested to know if you guys were able to keep `require watir/alerts`, we found in the betas this library was causing issues. Aside from that, everything was/is working great.

**Comment by titusfortner** [comment]
@MacCracken - FYI I had some issues with net-http-persistent 3.0, which is forcing the use of keywords instead of the ordered parameters that Selenium passes it. It needs to be updated in Selenium, but I wanted to point out that if you actually use persistent browser your tests will probably fail.

**Comment by MacCracken** [comment]
@titusfortner thanks, reverted back to 2.9

**Comment by cheezy** [comment]
I have a quick release that supports Selenium 3 that I want to push out today.  I am hoping to get a subsequent release out next week that has support for Watir 6.

**Comment by MacCracken** [comment]
Thanks @cheezy 
I'll look forward to seeing it soon.

**Comment by cheezy** [comment]
I have most of this merged manually.  I'm working toward a new release in the next couple of days that has support for Watir 6.  Thanks for your help.

**Pull request closed without merging**
