### PR TITLE
Fix #275

### LINKED ISSUE #275: "text is not available on button element in Selenium"
"text is not available on button element in Selenium" is confusing because `.text` does work, page-object just makes it a runtime error. How else are you suppose to get the inner text of a link?

- https://github.com/cheezy/page-object/blob/cf3f29d9e1dbf165ee196bfbdbfccd0b2641a606/lib/page-object/platforms/selenium_webdriver/button.rb#L10

I don't think page-object should randomly be removing parts of the selenium API and creating runtime errors. Would you accept a PR to remove this feature?

### PR DESCRIPTION
**Pull request by bootstraponline**
If the "button" is an anchor tag then .text will work as expected and shouldn't error.

### CODE REVIEW

**Comment by bootstraponline** [comment]
It looks like the Travis failure are unrelated to this fix.

**Comment by daneandersen** [comment]
@bootstraponline, I fixed the issue you mentioned in the master branch, so if you merge those changes into your branch, this might pass.

**Comment by bootstraponline** [comment]
Thanks. I updated the patch. I'll know in a few hours if the tests pass.

**Comment by bootstraponline** [comment]
It looks like all the tests pass.

**Comment by bootstraponline** [comment]
Closing as overriding selenium methods to raise exceptions is a feature not a bug.

**Pull request closed without merging**
