### PR TITLE
pass drag_and_drop_on to watir-webdriver

### PR DESCRIPTION
**Pull request by AlexisKAndersen**

### CODE REVIEW

**Comment by d-konovalov** [comment]
hi @daneandersen 
it's not clear at the moment it works or not?

**Comment by cheezy** [comment]
What is the status of this pr?  Is it still desired?

**Comment by daneandersen** [comment]
Someone had requested drag and drop functionality in page object. I was attempting to deliver it. If memory serves, it worked for me locally, but for whatever reason, it never passed in travis-ci.

**Comment by cheezy** [comment]
@daneandersen are you still interested in this capability?

**Comment by daneandersen** [comment]
I took it on because it seemed like an easy fix since it was just a pass through, but I had trouble getting it to work as intended in ci. I can take a look at it again and see if the current versions of everything do any better though.

**Pull request closed without merging**
