### PR TITLE
implementing focused? for issue-390

### PR DESCRIPTION
**Pull request by joesho112358**

### CODE REVIEW

**Comment by cheezy** [comment]
Would you have time to update this PR today to work with the latest in git?  I'm planning to make a release soon and would like to include this update.  If not, perhaps I can get to it later today.

**Comment by joesho112358** [comment]
I will be able to get to it tonight if that isn't too late.

**Comment by cheezy** [comment]
That will work.  I'm going to release the updated gem tomorrow morning.

**Comment by joesho112358** [comment]
@cheezy Should be good.

**Pull request merged**
