### PR TITLE
Better support for platforms

### PR DESCRIPTION
**Pull request by pvmeerbe**
Pull request as follow-up of  https://github.com/cheezy/page-object/pull/265

As suggested I tried creating a seperate gem to support watir nokogiri (https://github.com/pvmeerbe/page_object_watir_nokogiri), however the current implementation is limited/hardcoded for selenium & watir platforms only on some spots.

I made some modifications to allow easy addition of new platforms + allow easy inheritance of the existing platforms, for example WatirNokogiri platform inherits from Watir platform (see commit descriptions)

Spec & feature tests now provide same result as current master tree  (test on Feature: Gxt Table Extension fails as the related web site http://gxtexamplegallery.appspot.com/ is not available anymore) + new version of page object was tested on existing test suite using selenium-webdriver & watirnokogiri

### CODE REVIEW

**Comment by haploke** [comment]
Coolio :)

**Comment by bootstraponline** [comment]
What advantage is there to using nokogiri? [watir-nokogiri](https://github.com/jkotests/watir-nokogiri) appears to be dead.

**Comment by pvmeerbe** [comment]
I'm currently using water nokogiri in my projects and it still works perfectly.
Also, watir-nokogiri is just an example of another platform. My proposed changes easily allow to add   
any other platform to page-object.

The goal was to recycle the page-object logic which was implemented for feature testing using a browser, into integration tests ( example spec request tests) which do not use a browser but which do generate an HTML page as a result. WatirNokogiri fits perfectly for this.  Capybara implements something similar, but I do not want to use capybara as it adds an additional api layer on selenium-webdriver which is not used when using page-object. See https://github.com/cheezy/page-object/pull/265 for more details on background

**Comment by bootstraponline** [comment]
:+1:

**Comment by cheezy** [comment]
@pvmeerbe are you still using this feature? Is there still benefit in including it in the next release?

**Comment by cheezy** [comment]
@pvmeerbe I'm hoping to make a release soon and want to know if you are still using this feature and want it included.

**Comment by pvmeerbe** [comment]
@cheezy I'm still using this feature in my projects (currently using my fork)
Would be nice if this can be included

**Comment by cheezy** [comment]
@pvmeerbe I've merged the code.  I'll be making a release today.  Could you please add a page to the wiki explaining how to support a new platform?  Also, a page describing how to use watir-nokogiri and when/why one would do that would be fantastic.

**Comment by pvmeerbe** [comment]
@cheezy  thanks for merging

On adding a new platform: I more or less copy/pasted from the Watir platform and didn't investigate the nifty details on the how and the why as the Watir::Nokogiri platform is a subset of Watir. So I think its better that someone else explains this with more knowledge. 

Regarding the watir-nokogiri setup and usage  : something like this?  
https://github.com/cheezy/page-object/wiki/Use-Page-Object-On-Any-HTML-Fragment-Or-Page-(with-WatirNokogiri)

**Comment by jfair9** [comment]
I've done something very similar with using the RAutomation gem as a new platform to assist in using the PageObject pattern against a windows desktop application. Didn't go as far as refactoring the base PO Platform but rather "hardcoded" the additional platform into the code. I will have to pull your latest platform changes. Looks like I should be able to easily add this new platform without making any changes to PO code itself. Well done!

**Pull request merged**
