### PR TITLE
Default element tag to element

### LINKED ISSUE #302: Add default tag name to element
Instead of:

`element 'button', :element, css: 'some css'`

It'd be nice to have a default tag:

`element 'button', css: 'some css'`

I'm happy to submit a [pull request for this feature](https://github.com/bootstraponline/page_object/commit/9813f72eae0a85bd51a35a3f49a10d7732caaa86).

### PR DESCRIPTION
**Pull request by bootstraponline**
Fix #302

If this change is acceptable, let me know and I'll add tests before merging.

### CODE REVIEW

**Comment by daneandersen** [comment]
@bootstraponline, does this work in practice? I tried to write a test case for it, but it didn't seem to work as intended. If you write a test case that exercises it, I'll merge your pull request.

**Comment by bootstraponline** [comment]
Cool. I'll add a test to this PR and will comment when it's ready.

The feature works. I'm using this as part of my [angular_automation](https://github.com/bootstraponline/angular_automation). Here's an [example test](https://github.com/bootstraponline/sauce_connect_ruby/blob/5b6b4961c77372d739e81fe5fd516a9c1989676f/page/local_page.rb#L10) that demos the usage.

**Comment by bootstraponline** [comment]
I force pushed and added a test. I'd like to wait for Travis to run the test suite to make sure everything passes on all the ruby versions. If it's green then this should be ready to merge.

**Comment by bootstraponline** [comment]
It's passing on Travis and the code coverage increased.

**Comment by daneandersen** [comment]
:+1: Awesome, thanks!

**Comment by bootstraponline** [comment]
Thank you! This is the last feature I needed, now all my changes are upstream.

**Pull request merged**
